server:
  port: 8008
spring:
  data:
    mongodb:
      host: 192.168.157.11
      database: ns-saas
      port: 27017
      username: ns-admin
      password: 2b8ba2ded188!2b8ba2ded188@
      authentication-database: admin
