server:
  port: 8008
spring:
  data:
    mongodb:
      host: 172.21.0.141
      database: demo
      port: 27021
      username: ns-admin
      password: 2b8ba2ded188
      authentication-database: admin
# 入库数量
putIn: 10000
# 明细库
detailsLibrary: ""
# 诊断表库
diagnosisLibrary: ""
# 结算库
settlementOfPaymentLibrary: ""

# 租户id
corp_id: "nsn55n6h7kxm33v956ay"
# 明细分类id
detailsCategoryId: "nsn55n6h7kxm33v956ay"
# 诊断分类id
diagnosisCategoryId: "nsn55n6h7kxm33v956ay"
# 结算分类id
settlementOfPaymentCategoryId: "nsn55n6h7kxm33v956ay"
# 门诊间隔分类id
outPatientGapCategoryId: ""
# 住院间隔分类id
stayGapCategoryId: ""


diagnosis:
  # 就诊号
  eposide_id: 1
  # 出入院诊断类别
  inout_diag_type: 2
  # 诊断类别
  diag_type: 3
  # 是否为主诊
  main_flag: 4
  # 诊断代码
  diag_code: 5
  # 诊断名称
  diag_name: 6
  # 入院病情
  adm_cond: 7
  # 诊断科室
  diag_dept: 8
  # 诊断医师代码
  diag_dr_code: 9
  # 诊断医师姓名
  diag_dr_name: 10
  # 诊断时间
  diag_time: 11

settlementOfPayment:
  #结算单据号
  bill_id: 0
  #统筹区名称
  area_name: 0
  #参保人统筹区名称
  area_name_person: 0
  #定点机构编码
  medical_code: 0
  #定点机构名称
  medical_name: 0
  #定点机构类别
  medical_type: 0
  #定点机构等级
  medical_grade: 0
  #定点机构性质
  medical_nature: 0
  #社会保障卡号
  social_card: 0
  #患者证件号码
  card_id: 0
  #患者姓名
  patient_name: 1
  #患者出生日期 (转时间戳)
  birthday: 0
  #患者年龄
  age: 1
  #性别
  sex: 0
  #单位名称
  company_name: 0
  #险种类型
  benefit_type: 0
  #医疗类别
  medical_mode: 0
  #就诊号
  eposide_id: 0
  #费用结算时间 （时间戳）
  clear_time: 0
  #医疗费总额
  money_total: 14
  #医保范围费用
  money_medical: 14
  #特殊病种标识
  is_special: 0
  #入院日期
  in_date: 0
  #出院日期
  out_date: 0
  #住院天数
  hospital_num: 1
  #入院诊断疾病编码
  in_diagnose_code: 0
  #入院疾病名称
  in_diagnose_name: 0
  #出院疾病诊断编码
  out_diagnose_code: 0
  #出院疾病名称
  out_diagnose_name: 0
  #入院科室名称
  dept_name: 0
  #出院科室名称
  out_dept_name: 0
  #主治医生代码
  doctor_code: 0
  #主治医生
  doctor_name: 0
  #离院方式
  discharge_kind: 0
  #异地就诊标志
  nonlocal_org_sign: 0
details:
  #统筹区划代码
  area_code: 1
  #参保人统筹区代码
  area_person_code: 2
  #定点机构编码
  medical_code: 3
  #定点机构名称
  medical_name: 4
  #社会保障卡号
  social_card: 5
  #证件号码
  card_id: 6
  #人员编号
  psn_no: 7
  #姓名
  patient_name: 8
  #险种类型
  benefit_type: 9
  #医疗类别
  medical_mode: 10
  #就诊号
  eposide_id: 11
  #单据号
  bill_id: 12
  #单据明细号
  bill_detail_id: 13
  #门诊或住院号
  hospital_id: 14
  #费用发生时间
  cost_time: 15
  #费用结算时间
  clear_time: 16
  #
  item_code: 17
  #医保目录名称
  item_name: 18
  #机构收费项目编码
  item_code_hosp: 19
  #机构收费项目名称
  item_name_hosp: 20
  #收费项目类别
  charge_type: 21
  #费用类别
  cost_type: 22
  #单价
  unit_price: 23
  #限价
  max_price: 24
  #帖数
  dose: 25
  #数量
  num: 26
  #金额
  money: 27
  #自付比例
  pay_per_retio: 28
  #医保范围费用
  money_medical: 29
  #自理费用
  money_self_pay: 30
  #自费费用
  money_self_out: 31
  #剂型
  dosage_form: 32
  #规格
  spec: 33
  #药品剂型单位
  pack_unit: 34
  #生产企业
  bus_produce: 35
  #药品包装转化比
  pack_retio: 36
  #特殊病种标识
  is_special: 37
  #是否处方药
  is_recipel: 38
  #单复方标志
  is_single: 39
  #处方号
  recipel_no: 40
  #科室名称
  dept_name: 41
  #执行科室名称
  discharge_dept_name: 42
  #医生编码
  doctor_code: 43
  #医生姓名
  doctor_name: 44